### ISSUE TITLE
Getting errors in ios build, working fine in android

### ISSUE THREAD

**Issue by informsharique** [margelo/react-native-bignumber#41] opened 2022-04-13 00:46 UTC
I'm getting error something like this in ios build. In android app is compiled without any issues. Tried clearing RN cache. Re-installing node_modules and also deleting whole Pods folder and installing again. Nothing worked.

![image](https://user-images.githubusercontent.com/13877461/163077104-a4bce927-6415-46e8-a0d2-ad00082b0734.png)

**Comment by kantorm** [comment] 2022-04-27 08:11
Hey @mrousavy, I got the same error when building production variant on iOS. Here is the output from the command that you asked for.
```
Updating spec repo `cocoapods`
  $ /usr/bin/git -C /Users/michal/.cocoapods/repos/cocoapods fetch origin --progress
  remote: Enumerating objects: 15, done.
  remote: Counting objects: 100% (15/15), done.
  remote: Compressing objects: 100% (9/9), done.
  remote: Total 9 (delta 6), reused 0 (delta 0), pack-reused 0
  From https://github.com/CocoaPods/Specs
     2f702c72a0b3..1ff66cd869a3  master     -> origin/master
  $ /usr/bin/git -C /Users/michal/.cocoapods/repos/cocoapods rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/michal/.cocoapods/repos/cocoapods reset --hard origin/master
  HEAD is now at 1ff66cd869a3 [Add] GameFrameworkTool 1.1.2
Updating spec repo `trunk`
Auto-linking React Native modules for target `HammerWallet`: BVLinearGradient, RNBootSplash, RNCClipboard, RNDevMenu, RNDeviceInfo, RNGestureHandler, RNOS, RNReanimated, RNSVG, RNScreens, RNSentry, TcpSockets, VisionCamera, react-native-bignumber, react-native-config, react-native-flipper, react-native-get-random-values, react-native-mmkv, react-native-randombytes, react-native-restart, react-native-safe-area-context, react-native-udp, and vision-camera-code-scanner
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing BVLinearGradient (2.5.6)
Installing CocoaAsyncSocket (7.6.5)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.67.2)
Installing FBReactNativeSpec (0.67.2)
Installing Flipper (0.142.0)
Installing Flipper-Boost-iOSX (1.76.0.1.11)
Installing Flipper-DoubleConversion (3.1.7)
Installing Flipper-Fmt (7.1.7)
Installing Flipper-Folly (2.6.7)
Installing Flipper-Glog (0.3.6)
Installing Flipper-PeerTalk (0.0.4)
Installing Flipper-RSocket (1.4.3)
Installing FlipperKit (0.142.0)
Installing GTMSessionFetcher (1.7.1)
Installing GoogleDataTransport (9.1.2)
Installing GoogleMLKit (3.0.0)
Installing GoogleToolboxForMac (2.3.2)
Installing GoogleUtilities (7.7.0)
Installing GoogleUtilitiesComponents (1.1.0)
Installing MLImage (1.0.0-beta2)
Installing MLKitBarcodeScanning (2.0.0)
Installing MLKitCommon (6.0.0)
Installing MLKitVision (4.0.0)
Installing MMKV (1.2.13)
Installing MMKVCore (1.2.13)
Installing OpenSSL-Universal (1.1.180)
Installing PromisesObjC (2.1.0)
Installing Protobuf (3.20.1)
Installing RCT-Folly (2021.06.28.00-v2)
Installing RCTRequired (0.67.2)
Installing RCTTypeSafety (0.67.2)
Installing RNBootSplash (4.1.3)
Installing RNCClipboard (1.8.5)
Installing RNDevMenu (4.0.2)
Installing RNDeviceInfo (8.7.0)
Installing RNGestureHandler (2.3.0)
Installing RNOS (1.2.6)
Installing RNReanimated (2.4.1)
Installing RNSVG (12.3.0)
Installing RNScreens (3.13.1)
Installing RNSentry (3.3.1)
Installing React (0.67.2)
Installing React-Core (0.67.2)
Installing React-CoreModules (0.67.2)
Installing React-RCTActionSheet (0.67.2)
Installing React-RCTAnimation (0.67.2)
Installing React-RCTBlob (0.67.2)
Installing React-RCTImage (0.67.2)
Installing React-RCTLinking (0.67.2)
Installing React-RCTNetwork (0.67.2)
Installing React-RCTSettings (0.67.2)
Installing React-RCTText (0.67.2)
Installing React-RCTVibration (0.67.2)
Installing React-callinvoker (0.67.2)
Installing React-cxxreact (0.67.2)
Installing React-jsi (0.67.2)
Installing React-jsiexecutor (0.67.2)
Installing React-jsinspector (0.67.2)
Installing React-logger (0.67.2)
Installing React-perflogger (0.67.2)
Installing React-runtimeexecutor (0.67.2)
Installing ReactCommon (0.67.2)
Installing Sentry (7.10.0)
Installing SocketRocket (0.6.0)
Installing TcpSockets (3.3.2)
Installing VisionCamera (2.13.2)
Installing Yoga (1.14.0)
Installing YogaKit (1.18.1)
Installing boost (1.76.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing libevent (2.1.12)
Installing nanopb (2.30908.0)
Installing react-native-bignumber (0.1.7)
Installing react-native-config (1.4.5)
Installing react-native-flipper (0.142.0)
Installing react-native-get-random-values (1.7.2)
Installing react-native-mmkv (2.1.0)
Installing react-native-randombytes (3.6.1)
Installing react-native-restart (0.0.24)
Installing react-native-safe-area-context (3.4.1)
Installing react-native-udp (2.7.0)
Installing vision-camera-code-scanner (0.2.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 77 dependencies from the Podfile and 84 total pods installed.
```

**Comment by mrousavy** [comment] 2022-04-27 08:25
> Installing OpenSSL-Universal (1.1.180)

hmm, looks like everything's being installed correctly... 🤔 

could you share a reproduceable example? maybe try upgrading to RN 0.68?

**Comment by kantorm** [comment] 2022-04-27 12:31
I tried upgrade to RN 0.68 but it didn't help. [Here](https://github.com/kantorm/TestBignumberApp) is reproducible example repo. I'm not sure if it helps but I run on M1 chip.

**Comment by mrousavy** [comment] 2022-04-27 13:12
Thanks for the repro, we'll take a look once we got some free time!

To make sure: can you build and run the Example app here?

**Comment by kantorm** [comment] 2022-04-27 15:05
Yes the Example app works but only when I change iOS version in `Deployment Info` section to iOS 11.

**Comment by kantorm** [comment] 2022-05-05 15:06
Hi @mrousavy I had some time to debug this issue a bit more and it seems that it may be connected to flipper. When I comment out `use_flipper` in Podfile release configuration build runs without any errors. Do you think this might be it?

**Comment by mrousavy** [comment] 2022-05-05 15:07
Oh, yea Flipper also uses OpenSSL as a dependency, maybe that's the issue?

**Comment by margox** [comment] 2022-12-17 07:28
https://github.com/margelo/react-native-quick-crypto/issues/121

**Comment by Montchy** [comment] 2023-08-14 09:03
Thank you for posting you issue, but it is a duplicate of:

-https://github.com/margelo/react-native-bignumber/issues/59

**Closed by Montchy** 2023-08-14 09:03 UTC
